// SPDX-FileCopyrightText: 2025 Kwame, III <webarcherydev@gmail.com>
// SPDX-License-Identifier: BSD-3-Clause
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

// https://webarchery.dev
import "package:archery/archery/archery.dart";

/// Base type for many-to-many pivot table definitions.
///
/// A `PivotTable` describes the intermediate table used to connect two model
/// types in a `belongsToMany` relationship. It defines the pivot table name,
/// column schema, and migration behavior for supported database disks.
///
/// The generic types [T] and [U] represent the two related model types.
///
/// Example:
/// ```dart
/// class UserRolePivot extends PivotTable<User, Role> {
///   @override
///   late final Map<String, String> columnDefinitions = {
///     'user_id': 'INTEGER NOT NULL',
///     'role_id': 'INTEGER NOT NULL',
///   };
/// }
///
/// final pivot = UserRolePivot();
/// print(pivot.name); // user_role
/// ```
abstract class PivotTable<T extends Model, U extends Model> {
  /// Primary key value for the pivot record, when applicable.
  int? id;

  /// Timestamp indicating when the pivot record was created.
  DateTime? createdAt;

  /// Timestamp indicating when the pivot record was last updated.
  DateTime? updatedAt;

  /// Storage backend used by this pivot table.
  ///
  /// Defaults to [Model.defaultDisk].
  DatabaseDisk disk = Model.defaultDisk;

  /// Serializes the pivot record into a JSON-compatible map.
  ///
  /// Includes timestamp metadata but not the primary key.
  ///
  /// Example:
  /// ```dart
  /// final json = pivot.toJson();
  /// print(json['created_at']);
  /// print(json['updated_at']);
  /// ```
  Map<String, dynamic> toJson() {
    return {"created_at": createdAt, "updated_at": updatedAt};
  }

  /// Serializes the pivot record into a metadata-oriented JSON map.
  ///
  /// Includes the primary key and timestamp metadata.
  ///
  /// Example:
  /// ```dart
  /// final meta = pivot.toMetaJson();
  /// print(meta['id']);
  /// ```
  Map<String, dynamic> toMetaJson() {
    return {"id": id, "created_at": createdAt, "updated_at": updatedAt};
  }

  /// Returns the inferred pivot table name for [T] and [U].
  ///
  /// The name is generated by concatenating the type names and converting the
  /// result to snake_case.
  ///
  /// Example:
  /// ```dart
  /// class UserRolePivot extends PivotTable<User, Role> {
  ///   @override
  ///   late final Map<String, String> columnDefinitions = {
  ///     'user_id': 'INTEGER NOT NULL',
  ///     'role_id': 'INTEGER NOT NULL',
  ///   };
  /// }
  ///
  /// final pivot = UserRolePivot();
  /// print(pivot.name); // user_role
  /// ```
  String get name {
    final typeName = "$T$U";
    final snakeCase = typeName.replaceAllMapped(RegExp(r'(?<=[a-z])(?=[A-Z])'), (match) => '_');
    return snakeCase.toLowerCase();
  }

  /// Column definitions specific to the pivot relationship.
  ///
  /// Implementations typically define the two foreign key columns required by
  /// the relationship.
  ///
  /// Example:
  /// ```dart
  /// @override
  /// late final Map<String, String> columnDefinitions = {
  ///   'user_id': 'INTEGER NOT NULL',
  ///   'role_id': 'INTEGER NOT NULL',
  /// };
  /// ```
  late final Map<String, String> columnDefinitions;

  /// Default columns applied to all pivot tables.
  ///
  /// These include the primary key and timestamp fields.
  ///
  /// Example:
  /// ```dart
  /// print(PivotTable.defaultColumnDefinitions['id']);
  /// ```
  static Map<String, String> defaultColumnDefinitions = {'id': 'INTEGER PRIMARY KEY AUTOINCREMENT', 'created_at': 'TEXT NOT NULL', 'updated_at': 'TEXT NOT NULL'};

  /// Migrates the pivot table schema for the selected [disk].
  ///
  /// For SQLite, this method:
  /// - merges [defaultColumnDefinitions] with [columnDefinitions]
  /// - creates the pivot table if it does not exist
  /// - creates a standard composite index on the relationship columns
  /// - creates a unique composite index to prevent duplicate relationships
  ///
  /// At present, pivot table migration is implemented for `sqlite` only.
  ///
  /// Parameters:
  /// - `disk`: The target storage backend. Defaults to [Model.defaultDisk].
  ///
  /// Example:
  /// ```dart
  /// final pivot = UserRolePivot();
  /// await pivot.migrate(disk: DatabaseDisk.sqlite);
  /// ```
  Future<void> migrate({DatabaseDisk disk = Model.defaultDisk}) async {
    switch (disk) {
      case DatabaseDisk.sqlite:
        try {
          final database = App().make<SQLiteDatabase>();
          final allColumns = {...defaultColumnDefinitions, ...columnDefinitions};

          final col1 = columnDefinitions.keys.toList()[0].toString();
          final col2 = columnDefinitions.keys.toList()[1].toString();

          final columnsDef = allColumns.entries.map((e) => '${e.key} ${e.value}').join(', ');

          await database.execute('''
                CREATE TABLE IF NOT EXISTS $name (
                  $columnsDef
                )
                ''');
          await database.execute('''
                CREATE INDEX IF NOT EXISTS idx_$name ON $name ($col1, $col2)
                ''');
          await database.execute('''
               CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_$name ON $name ($col1, $col2)
                ''');
        } catch (e, stack) {
          App().archeryLogger.error("Error migrating pivot table: $name", {"origin": "PivotTable.migrate() case:sqlite", "error": e.toString(), "stack": stack.toString()});
        }

      case DatabaseDisk.file:
        // TODO: Handle this case.
        App().archeryLogger.error("Error migrating pivot table: $name", {"origin": "PivotTable.migrate() case:file", "error": "file disk not configured",});
        throw UnimplementedError();
      case DatabaseDisk.pgsql:
        App().archeryLogger.error("Error migrating pivot table: $name", {"origin": "PivotTable.migrate() case:pgsql", "error": "pgsql disk not configured",});
        throw UnimplementedError();
      case DatabaseDisk.s3:
        App().archeryLogger.error("Error migrating pivot table: $name", {"origin": "PivotTable.migrate() case:s3", "error": "s3 disk not configured",});
        throw UnimplementedError();
    }
  }
}
